<?php
$gambars=["1.jpg","2.webp","3.png"];
$pages=[
        "home"=>"index",
        "kontak"=>"kontak",
        "jurusan"=>"jurusan",
        "sejarah"=>"sejarah",
        "prestasi"=>"prestasi",
    ];